### ISSUE TITLE
[Enhancement] GitHub Actionsを利用した構文強制

### ISSUE THREAD

**Issue by daima3629** [Huyu2239/GChub#3]
Pythonの共同開発ではよく行われていますが、GitHub Actionsを利用してPull Request時に自動でflake8に構文をチェックさせる仕組みがあります。
ぜひ導入してみてはいかがでしょうか。
もし賛成意見多ければこちらでセットアップのPR出します。

**Comment by daima3629** [comment]
あ、でも先にpush権限もらわないとだめか。

**Comment by Huyu2239** [comment]
flake忘れてました、、
賛成です

**Comment by Nirezi** [comment]
PR時だけでなくコミットがあったとかで良さそう

**Comment by Huyu2239** [comment]
push権限ってどこで付与するんですか？

**Comment by daima3629** [comment]
あー、普通にCollaboratorの招待送ってくれれば
ってもう来てたわ

**Comment by daima3629** [comment]
> PR時だけでなくコミットがあったとかで良さそう

あー...そういう事を言いたかった
ちょっと寝起きだったので説明力が死んでた、申し訳ないです

**Comment by Huyu2239** [comment]
おねがいしてもいいですか？
@daima3629

**Comment by daima3629** [comment]
あ、じゃあセットアップのPR出しますねー

**Comment by Huyu2239** [comment]
お願いします～

**Comment by daima3629** [comment]
ってことでPR作ったのでレビューお願いします
