### ISSUE TITLE
Prefixをどうするか

### ISSUE THREAD

**Issue by sevenc-nanashi** [Huyu2239/GChub#7]
`$` だとかぶって大変なことになりそうだと思った。
`gc.`とかどうかな

**Comment by sevenc-nanashi** [comment]
（あくまで個人の感想です。）

**Comment by Shirataki2** [comment]
基本は`/`などで`get_prefix`の際にBotのニックネームを確認して`[$] GCBot`となっていれば`$`をprefixとするBotがあって賢いなと思ったので，デフォが`gc.`でニックネームを読み取ってギルドごとに変えるという方針でもいいかなと思います

**Comment by sevenc-nanashi** [comment]
これでいいかな

**Comment by Huyu2239** [comment]
おけです
