### ISSUE TITLE
運営していく上での方針

### ISSUE THREAD

**Issue by Huyu2239** [Huyu2239/GChub#8]
各チャンネルや各ユーザーのログを出力し、運営が削除するような方針か、ログは取らずに軽いものにする方針か悩んでいます

**Comment by daima3629** [comment]
ログは取ったほうがいいと思います
半永久的に残しておかないと問題が起こったとき対処がしづらいかと
一般ユーザーのいじれない場所にログを置いておけば、それに絶対的な信頼度があるので

**Comment by Huyu2239** [comment]
最初はサポートサーバーに参加しているユーザーのみ作成可能にして、そのユーザーのみが閲覧できるチャンネルを公式サーバーに作成し、そこにログを残して不適切な投稿があった場合に消してもらえるようにしようかと思っていたのですが、公式サーバー外でもできたほうがいいという意見が上がって取りやめたんです
こういう面での運営はどうしましょうか？（基本的な構造も出来上がってないので、ある程度出来上がってから決めようと思います）

**Comment by daima3629** [comment]
そもそもグローバルチャットに送信したメッセージは基本削除できない、不適切な投稿が合った場合は運営が消せるようにする、じゃだめなんですかね
ユーザーもポンポン消せるようにするとレート制限に引っかかる恐れがあるので

**Comment by Huyu2239** [comment]
分かりました
そうします
